name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
resources:
  - repo: self
    clean: true

jobs:

  ### Windows build ###
  - job: Windows_build
    displayName: Windows Build
    timeoutInMinutes: 75
    strategy:
      # Change maxParallel to 1 make builds run in serial rather than in parallel
      maxParallel: 100
      matrix:
        .Net Core 3.1:
          FRAMEWORK: netcoreapp3.1

    condition: succeeded()
    pool:
      vmImage: windows-2022

    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core SDK 3.1'
        inputs:
          packageType: sdk
          version: 3.1.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: PowerShell@2
        displayName: 'Show Repo Contents'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Source contents:"
            gci $(Build.SourcesDirectory)
            Write-Host "Binary content"
            gci $(Build.BinariesDirectory)
            Write-Host "Staging Content"
            gci $(Build.ArtifactStagingDirectory)
            Write-Host "Agent work folder"
            gci $(Agent.WorkFolder)
            Write-Host "System Default folder"
            gci $(System.DefaultWorkingDirectory)

      - task: PowerShell@2
        displayName: 'Build and package'
        inputs:
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/build.ps1'
          arguments: '-clean -configuration Release -build -package'
          workingDirectory: '$(System.ArtifactsDirectory)/_azure-iot-sdk-net'

      - task: PowerShell@2
        displayName: 'Add date for Packages'
        inputs:
          targetType: 'inline'
          script: |
            $file_date = get-date -f yyyy-MM-dd-hh-mm-ss.f
            Write-Host "Package contents:"
            gci $(System.ArtifactsDirectory)/_azure-iot-sdk-net/bin/pkg
            Write-Host " "
            Write-Host "\/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/"
            Write-Host "\/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/"
            Write-Host "The package name below is used in the partner release pipeline to identify files for signing"
            Write-Host " "
            Write-Host "azure-iot-sdk/net/pkgs_$file_date"
            Write-Host " "
            Write-Host "/\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\"
            Write-Host "/\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\ /\"
            Write-Host " "
            Rename-Item $(System.ArtifactsDirectory)/_azure-iot-sdk-net/bin/pkg $(System.ArtifactsDirectory)/_azure-iot-sdk-net/bin/pkgs_$file_date
        
