name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
resources:
  - repo: self
    clean: true

jobs:

  ### Windows build ###
  - job: Windows_Test
    displayName: Windows Build
    timeoutInMinutes: 200
    strategy:
      # Change maxParallel to 1 make builds run in serial rather than in parallel
      maxParallel: 1
      matrix:
        .Net Core 3.x:
          FRAMEWORK: netcoreapp3.1
          NUGET_DROP: true

    condition: succeeded()
    pool:
      vmImage: windows-2022

    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core SDK 2.x'
        inputs:
          packageType: sdk
          version: 2.1.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/net

      - task: UseDotNet@2
        displayName: 'Use .NET Core SDK 3.x'
        inputs:
          packageType: sdk
          version: 3.1.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/net

      - task: UseDotNet@2
        displayName: 'Use .NET SDK 5.x'
        inputs:
          packageType: sdk
          version: 5.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/net

      - task: UseDotNet@2
        displayName: 'Use .NET SDK 6.x'
        inputs:
          packageType: sdk
          version: 6.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/net

      - script: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          sn -Vr *,31bf3856ad364e35
        displayName: 'Disable strong name validation'

      - task: PowerShell@2
        displayName: 'Build Packages'
        inputs:
          targetType: 'inline'
          script: |
            $Env:NUGET_PKG_DATE = get-date -f yyyy-MM-dd-hh-mm-ss.f
            Write-Host Start building release package on $(Agent.Id):$(Agent.MachineName) on $ENV:NUGET_PKG_DATE
            $(Build.SourcesDirectory)/build.ps1 -build -clean -configuration Release -package

